rmq:
  host: 127.0.0.1
  user: erksystem
  password: erksystem.123
  port: 10001
  incoming-queue:
    api: API_QUEUE
    per-queue: PER_QUEUE
    ser-queue: SER_QUEUE
    fer-queue: FER_QUEUE
    ekm-queue: EKM_QUEUE
  outgoing-queue:
    api: ERK_API_QUEUE
    subsystem: ERK_SUBSYSTEM_QUEUE

scenario:
  steps:
    - send; api; /home/erksystem/simulator/resource/add_service_provider_info_rq_naver.json
    - pause; 1000
    - send; api; /home/erksystem/simulator/resource/del_service_provider_info_rq.json
    - pause; 1000
    - send; api; /home/erksystem/simulator/resource/add_user_info_req_naver.json
    - pause; 1000
    - send; subsystem; /