// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.3
package com.erksystem.protobuf.api;

public final class ErkApiMsgOuterClass {
  private ErkApiMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkMsgHead_s_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkMsgHead_s_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkMsgDataHead_s_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkMsgDataHead_s_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkInterMsgHead_s_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkInterMsgHead_s_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueueInfo_s_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueueInfo_s_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkEngineInfo_s_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkEngineInfo_s_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddServiceProviderInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddServiceProviderInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddServiceProviderInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddServiceProviderInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateServiceProviderInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateServiceProviderInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateServiceProviderInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateServiceProviderInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelServiceProviderInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelServiceProviderInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelServiceProviderInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelServiceProviderInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddUserInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddUserInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelUserInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelUserInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelUserInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelUserInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceConnRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceConnRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceConnRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceConnRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceDisConnRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceDisConnRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceDisConnRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceDisConnRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoServiceStartRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoServiceStartRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoServiceStartRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoServiceStartRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoServiceStopRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoServiceStopRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoServiceStopRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoServiceStopRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkEngineCreateRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkEngineCreateRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkEngineCreateRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkEngineCreateRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkEngineDeleteRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkEngineDeleteRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkEngineDeleteRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkEngineDeleteRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PhysioEmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PhysioEmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PhysioEmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PhysioEmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechEmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechEmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechEmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechEmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaceEmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaceEmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaceEmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaceEmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogNoti_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogNoti_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkApiMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkApiMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ErkApiMsg.proto\"n\n\014ErkMsgHead_s\022\036\n\007Msg" +
      "Type\030\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQueueInfo\030\002" +
      " \001(\0132\014.QueueInfo_s\022\r\n\005OrgId\030\003 \001(\005\022\016\n\006Use" +
      "rId\030\004 \001(\005\"r\n\020ErkMsgDataHead_s\022\036\n\007MsgType" +
      "\030\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQueueInfo\030\002 \001(\013" +
      "2\014.QueueInfo_s\022\r\n\005OrgId\030\003 \001(\005\022\016\n\006UserId\030" +
      "\004 \001(\005\"W\n\021ErkInterMsgHead_s\022#\n\007MsgType\030\001 " +
      "\001(\0162\022.ErkInterMsgType_e\022\r\n\005OrgId\030\002 \001(\005\022\016" +
      "\n\006UserId\030\003 \001(\005\"9\n\013QueueInfo_s\022\023\n\013ToQueue" +
      "Name\030\001 \001(\t\022\025\n\rFromQueueName\030\002 \001(\t\"\242\001\n\017Er" +
      "kEngineInfo_s\022!\n\nEngineType\030\001 \001(\0162\r.Engi" +
      "neType_e\022+\n\017EngineCondition\030\002 \001(\0162\022.Engi" +
      "neCondition_e\022\016\n\006IpAddr\030\003 \001(\t\022\030\n\020Receive" +
      "QueueName\030\004 \001(\t\022\025\n\rSendQueueName\030\005 \001(\t\"\367" +
      "\001\n\032AddServiceProviderInfoRQ_m\022\036\n\007MsgType" +
      "\030\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQueueInfo\030\002 \001(\013" +
      "2\014.QueueInfo_s\022\017\n\007OrgName\030\003 \001(\t\022\016\n\006OrgPw" +
      "d\030\004 \001(\t\022%\n\014ProviderType\030\005 \001(\0162\017.Provider" +
      "Type_e\022\027\n\017ServiceDuration\030\006 \001(\t\022\022\n\nUserN" +
      "umber\030\007 \001(\005\022#\n\013ServiceType\030\010 \001(\0162\016.Servi" +
      "ceType_e\"\257\002\n\032AddServiceProviderInfoRP_m\022" +
      "\036\n\007MsgType\030\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQueue" +
      "Info\030\002 \001(\0132\014.QueueInfo_s\022\017\n\007OrgName\030\003 \001(" +
      "\t\022\'\n\nResultType\030\004 \001(\0162\023.OrgProfileResult" +
      "_e\022\r\n\005OrgId\030\005 \001(\005\022\016\n\006OrgPwd\030\006 \001(\t\022%\n\014Pro" +
      "viderType\030\007 \001(\0162\017.ProviderType_e\022\027\n\017Serv" +
      "iceDuration\030\010 \001(\t\022\022\n\nUserNumber\030\t \001(\005\022#\n" +
      "\013ServiceType\030\n \001(\0162\016.ServiceType_e\"\253\003\n\035U" +
      "pdateServiceProviderInfoRQ_m\022\036\n\007MsgType\030" +
      "\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQueueInfo\030\002 \001(\0132" +
      "\014.QueueInfo_s\022\017\n\007OrgName\030\003 \001(\t\022\022\n\nOld_Or" +
      "gPwd\030\004 \001(\t\022)\n\020Old_ProviderType\030\005 \001(\0162\017.P" +
      "roviderType_e\022\033\n\023Old_ServiceDuration\030\006 \001" +
      "(\t\022\026\n\016Old_UserNumber\030\007 \001(\005\022\'\n\017Old_Servic" +
      "eType\030\010 \001(\0162\016.ServiceType_e\022\022\n\nNew_OrgPw" +
      "d\030\t \001(\t\022)\n\020New_ProviderType\030\n \001(\0162\017.Prov" +
      "iderType_e\022\033\n\023New_ServiceDuration\030\013 \001(\t\022" +
      "\026\n\016New_UserNumber\030\014 \001(\005\022\'\n\017New_ServiceTy" +
      "pe\030\r \001(\0162\016.ServiceType_e\"\324\003\n\035UpdateServi" +
      "ceProviderInfoRP_m\022\036\n\007MsgType\030\001 \001(\0162\r.Er" +
      "kMsgType_e\022\037\n\tQueueInfo\030\002 \001(\0132\014.QueueInf" +
      "o_s\022\017\n\007OrgName\030\003 \001(\t\022\'\n\nResultType\030\004 \001(\016" +
      "2\023.OrgProfileResult_e\022\022\n\nOld_OrgPwd\030\005 \001(" +
      "\t\022)\n\020Old_ProviderType\030\006 \001(\0162\017.ProviderTy" +
      "pe_e\022\033\n\023Old_ServiceDuration\030\007 \001(\t\022\026\n\016Old" +
      "_UserNumber\030\010 \001(\005\022\'\n\017Old_ServiceType\030\t \001" +
      "(\0162\016.ServiceType_e\022\022\n\nNew_OrgPwd\030\n \001(\t\022)" +
      "\n\020New_ProviderType\030\013 \001(\0162\017.ProviderType_" +
      "e\022\033\n\023New_ServiceDuration\030x \001(\t\022\026\n\016New_Us" +
      "erNumber\030\r \001(\005\022\'\n\017New_ServiceType\030\016 \001(\0162" +
      "\016.ServiceType_e\"~\n\032DelServiceProviderInf" +
      "oRQ_m\022\036\n\007MsgType\030\001 \001(\0162\r.ErkMsgType_e\022\037\n" +
      "\tQueueInfo\030\002 \001(\0132\014.QueueInfo_s\022\017\n\007OrgNam" +
      "e\030\003 \001(\t\022\016\n\006OrgPwd\030\004 \001(\t\"\227\001\n\032DelServicePr" +
      "oviderInfoRP_m\022\036\n\007MsgType\030\001 \001(\0162\r.ErkMsg" +
      "Type_e\022\037\n\tQueueInfo\030\002 \001(\0132\014.QueueInfo_s\022" +
      "\017\n\007OrgName\030\003 \001(\t\022\'\n\nResultType\030\004 \001(\0162\023.O" +
      "rgProfileResult_e\"\250\002\n\017AddUserInfoRQ_m\022\036\n" +
      "\007MsgType\030\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQueueIn" +
      "fo\030\002 \001(\0132\014.QueueInfo_s\022\017\n\007OrgName\030\003 \001(\t\022" +
      "\020\n\010UserName\030\004 \001(\t\022\017\n\007UserPwd\030\005 \001(\t\022\027\n\017Se" +
      "rviceDuration\030\006 \001(\t\022\013\n\003Age\030\007 \001(\005\022\027\n\003Sex\030" +
      "\010 \001(\0162\n.SexType_e\022\035\n\010MbtiType\030\t \001(\0162\013.Mb" +
      "tiType_e\022\035\n\010UserType\030\n \001(\0162\013.UserType_e\022" +
      "#\n\013ServiceType\030\013 \001(\0162\016.ServiceType_e\"\342\002\n" +
      "\017AddUserInfoRP_m\022\036\n\007MsgType\030\001 \001(\0162\r.ErkM" +
      "sgType_e\022\037\n\tQueueInfo\030\002 \001(\0132\014.QueueInfo_" +
      "s\022\017\n\007OrgName\030\003 \001(\t\022\020\n\010UserName\030\004 \001(\t\022(\n\n" +
      "ResultType\030\005 \001(\0162\024.UserProfileResult_e\022\016" +
      "\n\006UserId\030\006 \001(\005\022\017\n\007UserPwd\030\007 \001(\t\022\027\n\017Servi" +
      "ceDuration\030\010 \001(\t\022\013\n\003Age\030\t \001(\005\022\027\n\003Sex\030\n \001" +
      "(\0162\n.SexType_e\022\035\n\010MbtiType\030\013 \001(\0162\013.MbtiT" +
      "ype_e\022\035\n\010UserType\030\014 \001(\0162\013.UserType_e\022#\n\013" +
      "ServiceType\030\r \001(\0162\016.ServiceType_e\"\270\004\n\022Up" +
      "dateUserInfoRQ_m\022\036\n\007MsgType\030\001 \001(\0162\r.ErkM" +
      "sgType_e\022\037\n\tQueueInfo\030\002 \001(\0132\014.QueueInfo_" +
      "s\022\017\n\007OrgName\030\003 \001(\t\022\020\n\010UserName\030\004 \001(\t\022\023\n\013" +
      "Old_UserPwd\030\005 \001(\t\022\033\n\023Old_ServiceDuration" +
      "\030\006 \001(\t\022\024\n\007Old_Age\030\007 \001(\005H\000\210\001\001\022\033\n\007Old_Sex\030" +
      "\010 \001(\0162\n.SexType_e\022!\n\014Old_MbtiType\030\t \001(\0162" +
      "\013.MbtiType_e\022!\n\014Old_UserType\030\n \001(\0162\013.Use" +
      "rType_e\022\'\n\017Old_ServiceType\030\013 \001(\0162\016.Servi" +
      "ceType_e\022\023\n\013New_UserPwd\030\014 \001(\t\022\033\n\023New_Ser" +
      "viceDuration\030\r \001(\t\022\024\n\007New_Age\030\016 \001(\005H\001\210\001\001" +
      "\022\033\n\007New_Sex\030\017 \001(\0162\n.SexType_e\022!\n\014New_Mbt" +
      "iType\030\020 \001(\0162\013.MbtiType_e\022!\n\014New_UserType" +
      "\030\021 \001(\0162\013.UserType_e\022\'\n\017New_ServiceType\030\022" +
      " \001(\0162\016.ServiceType_eB\n\n\010_Old_AgeB\n\n\010_New" +
      "_Age\"\300\004\n\022UpdateUserInfoRP_m\022\036\n\007MsgType\030\001" +
      " \001(\0162\r.ErkMsgType_e\022\037\n\tQueueInfo\030\002 \001(\0132\014" +
      ".QueueInfo_s\022\017\n\007OrgName\030\003 \001(\t\022\020\n\010UserNam" +
      "e\030\004 \001(\t\022(\n\nResultType\030\005 \001(\0162\024.UserProfil" +
      "eResult_e\022\023\n\013Old_UserPwd\030\006 \001(\t\022\033\n\023Old_Se" +
      "rviceDuration\030\007 \001(\t\022\017\n\007Old_Age\030\010 \001(\005\022\033\n\007" +
      "Old_Sex\030\t \001(\0162\n.SexType_e\022!\n\014Old_MbtiTyp" +
      "e\030\n \001(\0162\013.MbtiType_e\022!\n\014Old_UserType\030\013 \001" +
      "(\0162\013.UserType_e\022\'\n\017Old_ServiceType\030\014 \001(\016" +
      "2\016.ServiceType_e\022\023\n\013New_UserPwd\030\r \001(\t\022\033\n" +
      "\023New_ServiceDuration\030\016 \001(\t\022\017\n\007New_Age\030\017 " +
      "\001(\005\022\033\n\007New_Sex\030\020 \001(\0162\n.SexType_e\022!\n\014New_" +
      "MbtiType\030\021 \001(\0162\013.MbtiType_e\022!\n\014New_UserT" +
      "ype\030\022 \001(\0162\013.UserType_e\022\'\n\017New_ServiceTyp" +
      "e\030\023 \001(\0162\016.ServiceType_e\"\206\001\n\017DelUserInfoR" +
      "Q_m\022\036\n\007MsgType\030\001 \001(\0162\r.ErkMsgType_e\022\037\n\tQ" +
      "ueueInfo\030\002 \001(\0132\014.QueueInfo_s\022\017\n\007OrgName\030" +
      "\003 \001(\t\022\020\n\010UserName\030\004 \001(\t\022\017\n\007UserPwd\030\005 \001(\t" +
      "\"\257\001\n\017DelUserInfoRP_m\022\036\n\007MsgType\030\001 \001(\0162\r." +
      "ErkMsgType_e\022\037\n\tQueueInfo\030\002 \001(\0132\014.QueueI" +
      "nfo_s\022\017\n\007OrgName\030\003 \001(\t\022\020\n\010UserName\030\004 \001(\t" +
      "\022(\n\nResultType\030\005 \001(\0162\024.UserProfileResult" +
      "_e\022\016\n\006Return\030\006 \001(\t\"H\n\022ErkServiceConnRQ_m" +
      "\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHead_s\022\017\n\007M" +
      "sgTime\030\002 \001(\003\"\220\001\n\022ErkServiceConnRP_m\022!\n\nE" +
      "rkMsgHead\030\001 \001(\0132\r.ErkMsgHead_s\022\017\n\007MsgTim" +
      "e\030\002 \001(\003\022!\n\nReturnCode\030\003 \001(\0162\r.ReturnCode" +
      "_e\022#\n\013ServiceType\030\004 \001(\0162\016.ServiceType_e\"" +
      "p\n\025ErkServiceDisConnRQ_m\022!\n\nErkMsgHead\030\001" +
      " \001(\0132\r.ErkMsgHead_s\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013" +
      "ServiceType\030\003 \001(\0162\016.ServiceType_e\"n\n\025Erk" +
      "ServiceDisConnRP_m\022!\n\nErkMsgHead\030\001 \001(\0132\r" +
      ".ErkMsgHead_s\022\017\n\007MsgTime\030\002 \001(\003\022!\n\nReturn" +
      "Code\030\003 \001(\0162\r.ReturnCode_e\"n\n\023EmoServiceS" +
      "tartRQ_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHea" +
      "d_s\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013ServiceType\030\003 \001(" +
      "\0162\016.ServiceType_e\"\312\002\n\023EmoServiceStartRP_" +
      "m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHead_s\022\017\n\007" +
      "MsgTime\030\002 \001(\003\022!\n\nReturnCode\030\003 \001(\0162\r.Retu" +
      "rnCode_e\022*\n\020PhysioEngineInfo\030\004 \001(\0132\020.Erk" +
      "EngineInfo_s\022*\n\020SpeechEngineInfo\030\005 \001(\0132\020" +
      ".ErkEngineInfo_s\022(\n\016FaceEngineInfo\030\006 \001(\013" +
      "2\020.ErkEngineInfo_s\022-\n\023KnowledgeEngineInf" +
      "o\030\007 \001(\0132\020.ErkEngineInfo_s\022+\n\021ServiceEngi" +
      "neInfo\030\010 \001(\0132\020.ErkEngineInfo_s\"\233\003\n\022EmoSe" +
      "rviceStopRQ_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkM" +
      "sgHead_s\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013ServiceType" +
      "\030\003 \001(\0162\016.ServiceType_e\022%\n\035PhysioEngine_R" +
      "eceiveQueueName\030\004 \001(\t\022\"\n\032PhysioEngine_Se" +
      "ndQueueName\030\005 \001(\t\022%\n\035SpeechEngine_Receiv" +
      "eQueueName\030\006 \001(\t\022\"\n\032SpeechEngine_SendQue" +
      "ueName\030\007 \001(\t\022#\n\033FaceEngine_ReceiveQueueN" +
      "ame\030\010 \001(\t\022 \n\030FaceEngine_SendQueueName\030\t " +
      "\001(\t\022(\n KnowledgeEngine_ReceiveQueueName\030" +
      "\n \001(\t\022%\n\035KnowledgeEngine_SendQueueName\030\013" +
      " \001(\t\"\311\002\n\022EmoServiceStopRP_m\022!\n\nErkMsgHea" +
      "d\030\001 \001(\0132\r.ErkMsgHead_s\022\017\n\007MsgTime\030\002 \001(\003\022" +
      "!\n\nReturnCode\030\003 \001(\0162\r.ReturnCode_e\022*\n\020Ph" +
      "ysioEngineInfo\030\004 \001(\0132\020.ErkEngineInfo_s\022*" +
      "\n\020SpeechEngineInfo\030\005 \001(\0132\020.ErkEngineInfo" +
      "_s\022(\n\016FaceEngineInfo\030\006 \001(\0132\020.ErkEngineIn" +
      "fo_s\022-\n\023KnowledgeEngineInfo\030\007 \001(\0132\020.ErkE" +
      "ngineInfo_s\022+\n\021ServiceEngineInfo\030\010 \001(\0132\020" +
      ".ErkEngineInfo_s\"\246\003\n\023ErkEngineCreateRQ_m" +
      "\022+\n\017ErkInterMsgHead\030\001 \001(\0132\022.ErkInterMsgH" +
      "ead_s\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013ServiceType\030\003 " +
      "\001(\0162\016.ServiceType_e\022%\n\035PhysioEngine_Rece" +
      "iveQueueName\030\004 \001(\t\022\"\n\032PhysioEngine_SendQ" +
      "ueueName\030\005 \001(\t\022%\n\035SpeechEngine_ReceiveQu" +
      "eueName\030\006 \001(\t\022\"\n\032SpeechEngine_SendQueueN" +
      "ame\030\007 \001(\t\022#\n\033FaceEngine_ReceiveQueueName" +
      "\030\010 \001(\t\022 \n\030FaceEngine_SendQueueName\030\t \001(\t" +
      "\022(\n KnowledgeEngine_ReceiveQueueName\030\n \001" +
      "(\t\022%\n\035KnowledgeEngine_SendQueueName\030\013 \001(" +
      "\t\"\324\002\n\023ErkEngineCreateRP_m\022+\n\017ErkInterMsg" +
      "Head\030\001 \001(\0132\022.ErkInterMsgHead_s\022\017\n\007MsgTim" +
      "e\030\002 \001(\003\022!\n\nReturnCode\030\003 \001(\0162\r.ReturnCode" +
      "_e\022*\n\020PhysioEngineInfo\030\004 \001(\0132\020.ErkEngine" +
      "Info_s\022*\n\020SpeechEngineInfo\030\005 \001(\0132\020.ErkEn" +
      "gineInfo_s\022(\n\016FaceEngineInfo\030\006 \001(\0132\020.Erk" +
      "EngineInfo_s\022-\n\023KnowledgeEngineInfo\030\007 \001(" +
      "\0132\020.ErkEngineInfo_s\022+\n\021ServiceEngineInfo" +
      "\030\010 \001(\0132\020.ErkEngineInfo_s\"\246\003\n\023ErkEngineDe" +
      "leteRQ_m\022+\n\017ErkInterMsgHead\030\001 \001(\0132\022.ErkI" +
      "nterMsgHead_s\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013Servic" +
      "eType\030\003 \001(\0162\016.ServiceType_e\022%\n\035PhysioEng" +
      "ine_ReceiveQueueName\030\004 \001(\t\022\"\n\032PhysioEngi" +
      "ne_SendQueueName\030\005 \001(\t\022%\n\035SpeechEngine_R" +
      "eceiveQueueName\030\006 \001(\t\022\"\n\032SpeechEngine_Se" +
      "ndQueueName\030\007 \001(\t\022#\n\033FaceEngine_ReceiveQ" +
      "ueueName\030\010 \001(\t\022 \n\030FaceEngine_SendQueueNa" +
      "me\030\t \001(\t\022(\n KnowledgeEngine_ReceiveQueue" +
      "Name\030\n \001(\t\022%\n\035KnowledgeEngine_SendQueueN" +
      "ame\030\013 \001(\t\"\324\002\n\023ErkEngineDeleteRP_m\022+\n\017Erk" +
      "InterMsgHead\030\001 \001(\0132\022.ErkInterMsgHead_s\022\017" +
      "\n\007MsgTime\030\002 \001(\003\022!\n\nReturnCode\030\003 \001(\0162\r.Re" +
      "turnCode_e\022*\n\020PhysioEngineInfo\030\004 \001(\0132\020.E" +
      "rkEngineInfo_s\022*\n\020SpeechEngineInfo\030\005 \001(\013" +
      "2\020.ErkEngineInfo_s\022(\n\016FaceEngineInfo\030\006 \001" +
      "(\0132\020.ErkEngineInfo_s\022-\n\023KnowledgeEngineI" +
      "nfo\030\007 \001(\0132\020.ErkEngineInfo_s\022+\n\021ServiceEn" +
      "gineInfo\030\010 \001(\0132\020.ErkEngineInfo_s\"E\n\rHear" +
      "tBeatRQ_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHe" +
      "ad_s\022\021\n\tQueueName\030\002 \001(\t\"B\n\rHeartBeatRP_m" +
      "\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHead_s\022\016\n\006S" +
      "tatus\030\002 \001(\005\"}\n\014EmoRecogRQ_m\022)\n\016ErkMsgDat" +
      "aHead\030\001 \001(\0132\021.ErkMsgDataHead_s\022\025\n\rDataTi" +
      "meStamp\030\002 \001(\003\022\025\n\rMsgDataLength\030\003 \001(\005\022\024\n\014" +
      "MsgDataFrame\030\004 \003(\014\"\245\001\n\014EmoRecogRP_m\022)\n\016E" +
      "rkMsgDataHead\030\001 \001(\0132\021.ErkMsgDataHead_s\022!" +
      "\n\nReturnCode\030\002 \001(\0162\r.ReturnCode_e\022\024\n\014Emo" +
      "RecogTime\030\003 \001(\003\022\037\n\007Emotion\030\004 \001(\0162\016.Emoti" +
      "onType_e\022\020\n\010Accuracy\030\005 \001(\002\"\203\001\n\022PhysioEmo" +
      "RecogRQ_m\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021.ErkM" +
      "sgDataHead_s\022\025\n\rDataTimeStamp\030\002 \001(\003\022\025\n\rM" +
      "sgDataLength\030\003 \001(\005\022\024\n\014MsgDataFrame\030\004 \003(\014" +
      "\"\253\001\n\022PhysioEmoRecogRP_m\022)\n\016ErkMsgDataHea" +
      "d\030\001 \001(\0132\021.ErkMsgDataHead_s\022!\n\nReturnCode" +
      "\030\002 \001(\0162\r.ReturnCode_e\022\024\n\014EmoRecogTime\030\003 " +
      "\001(\003\022\037\n\007Emotion\030\004 \001(\0162\016.EmotionType_e\022\020\n\010" +
      "Accuracy\030\005 \001(\002\"\203\001\n\022SpeechEmoRecogRQ_m\022)\n" +
      "\016ErkMsgDataHead\030\001 \001(\0132\021.ErkMsgDataHead_s" +
      "\022\025\n\rDataTimeStamp\030\002 \001(\003\022\025\n\rMsgDataLength" +
      "\030\003 \001(\005\022\024\n\014MsgDataFrame\030\004 \003(\014\"\253\001\n\022SpeechE" +
      "moRecogRP_m\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021.Er" +
      "kMsgDataHead_s\022!\n\nReturnCode\030\002 \001(\0162\r.Ret" +
      "urnCode_e\022\024\n\014EmoRecogTime\030\003 \001(\003\022\037\n\007Emoti" +
      "on\030\004 \001(\0162\016.EmotionType_e\022\020\n\010Accuracy\030\005 \001" +
      "(\002\"\201\001\n\020FaceEmoRecogRQ_m\022)\n\016ErkMsgDataHea" +
      "d\030\001 \001(\0132\021.ErkMsgDataHead_s\022\025\n\rDataTimeSt" +
      "amp\030\002 \001(\003\022\025\n\rMsgDataLength\030\003 \001(\005\022\024\n\014MsgD" +
      "ataFrame\030\004 \003(\014\"\251\001\n\020FaceEmoRecogRP_m\022)\n\016E" +
      "rkMsgDataHead\030\001 \001(\0132\021.ErkMsgDataHead_s\022!" +
      "\n\nReturnCode\030\002 \001(\0162\r.ReturnCode_e\022\024\n\014Emo" +
      "RecogTime\030\003 \001(\003\022\037\n\007Emotion\030\004 \001(\0162\016.Emoti" +
      "onType_e\022\020\n\010Accuracy\030\005 \001(\002\"\204\001\n\016EmoRecogN" +
      "oti_m\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021.ErkMsgDa" +
      "taHead_s\022\024\n\014EmoRecogTime\030\002 \001(\003\022\037\n\007Emotio" +
      "n\030\003 \001(\0162\016.EmotionType_e\022\020\n\010Accuracy\030\004 \001(" +
      "\002\"\365\r\n\tErkApiMsg\022?\n\030AddServiceProviderInf" +
      "oRQ\030\001 \001(\0132\033.AddServiceProviderInfoRQ_mH\000" +
      "\022?\n\030AddServiceProviderInfoRP\030\002 \001(\0132\033.Add" +
      "ServiceProviderInfoRP_mH\000\022E\n\033UpdateServi" +
      "ceProviderInfoRQ\030\003 \001(\0132\036.UpdateServicePr" +
      "oviderInfoRQ_mH\000\022E\n\033UpdateServiceProvide" +
      "rInfoRP\030\004 \001(\0132\036.UpdateServiceProviderInf" +
      "oRP_mH\000\022?\n\030DelServiceProviderInfoRQ\030\005 \001(" +
      "\0132\033.DelServiceProviderInfoRQ_mH\000\022?\n\030DelS" +
      "erviceProviderInfoRP\030\006 \001(\0132\033.DelServiceP" +
      "roviderInfoRP_mH\000\022)\n\rAddUserInfoRQ\030\007 \001(\013" +
      "2\020.AddUserInfoRQ_mH\000\022)\n\rAddUserInfoRP\030\010 " +
      "\001(\0132\020.AddUserInfoRP_mH\000\022/\n\020UpdateUserInf" +
      "oRQ\030\t \001(\0132\023.UpdateUserInfoRQ_mH\000\022/\n\020Upda" +
      "teUserInfoRP\030\n \001(\0132\023.UpdateUserInfoRP_mH" +
      "\000\022)\n\rDelUserInfoRQ\030\013 \001(\0132\020.DelUserInfoRQ" +
      "_mH\000\022)\n\rDelUserInfoRP\030\014 \001(\0132\020.DelUserInf" +
      "oRP_mH\000\022/\n\020ErkServiceConnRQ\030\r \001(\0132\023.ErkS" +
      "erviceConnRQ_mH\000\022/\n\020ErkServiceConnRP\030\016 \001" +
      "(\0132\023.ErkServiceConnRP_mH\000\0225\n\023ErkServiceD" +
      "isConnRQ\030\017 \001(\0132\026.ErkServiceDisConnRQ_mH\000" +
      "\0225\n\023ErkServiceDisConnRP\030\020 \001(\0132\026.ErkServi" +
      "ceDisConnRP_mH\000\0221\n\021EmoServiceStartRQ\030\021 \001" +
      "(\0132\024.EmoServiceStartRQ_mH\000\0221\n\021EmoService" +
      "StartRP\030\022 \001(\0132\024.EmoServiceStartRP_mH\000\022/\n" +
      "\020EmoServiceStopRQ\030\023 \001(\0132\023.EmoServiceStop" +
      "RQ_mH\000\022/\n\020EmoServiceStopRP\030\024 \001(\0132\023.EmoSe" +
      "rviceStopRP_mH\000\0221\n\021ErkEngineCreateRQ\030\025 \001" +
      "(\0132\024.ErkEngineCreateRQ_mH\000\0221\n\021ErkEngineC" +
      "reateRP\030\026 \001(\0132\024.ErkEngineCreateRP_mH\000\0221\n" +
      "\021ErkEngineDeleteRQ\030\027 \001(\0132\024.ErkEngineDele" +
      "teRQ_mH\000\0221\n\021ErkEngineDeleteRP\030\030 \001(\0132\024.Er" +
      "kEngineDeleteRP_mH\000\022%\n\013HeartBeatRQ\030\031 \001(\013" +
      "2\016.HeartBeatRQ_mH\000\022%\n\013HeartBeatRP\030\032 \001(\0132" +
      "\016.HeartBeatRP_mH\000\022#\n\nEmoRecogRQ\030\033 \001(\0132\r." +
      "EmoRecogRQ_mH\000\022#\n\nEmoRecogRP\030\034 \001(\0132\r.Emo" +
      "RecogRP_mH\000\022/\n\020PhysioEmoRecogRQ\030\035 \001(\0132\023." +
      "PhysioEmoRecogRQ_mH\000\022/\n\020PhysioEmoRecogRP" +
      "\030\036 \001(\0132\023.PhysioEmoRecogRP_mH\000\022/\n\020SpeechE" +
      "moRecogRQ\030\037 \001(\0132\023.SpeechEmoRecogRQ_mH\000\022/" +
      "\n\020SpeechEmoRecogRP\030  \001(\0132\023.SpeechEmoReco" +
      "gRP_mH\000\022+\n\016FaceEmoRecogRQ\030! \001(\0132\021.FaceEm" +
      "oRecogRQ_mH\000\022+\n\016FaceEmoRecogRP\030\" \001(\0132\021.F" +
      "aceEmoRecogRP_mH\000\022\'\n\014EmoRecogNoti\030# \001(\0132" +
      "\017.EmoRecogNoti_mH\000B\005\n\003msg*\372\005\n\014ErkMsgType" +
      "_e\022\026\n\022ErkMsgType_unknown\020\000\022\034\n\030AddService" +
      "ProviderInfoRQ\020\001\022\034\n\030AddServiceProviderIn" +
      "foRP\020\002\022\034\n\030DelServiceProviderInfoRQ\020\003\022\034\n\030" +
      "DelServiceProviderInfoRP\020\004\022\034\n\030UpdService" +
      "ProviderInfoRQ\020\005\022\034\n\030UpdServiceProviderIn" +
      "foRP\020\006\022\021\n\rAddUserInfoRQ\020\007\022\021\n\rAddUserInfo" +
      "RP\020\010\022\021\n\rDelUserInfoRQ\020\t\022\021\n\rDelUserInfoRP" +
      "\020\n\022\021\n\rUpdUserInfoRQ\020\013\022\021\n\rUpdUserInfoRP\020\014" +
      "\022\024\n\020ErkServiceConnRQ\020\r\022\024\n\020ErkServiceConn" +
      "RP\020\016\022\027\n\023ErkServiceDisConnRQ\020\017\022\027\n\023ErkServ" +
      "iceDisConnRP\020\020\022\025\n\021EmoServiceStartRQ\020\021\022\025\n" +
      "\021EmoServiceStartRP\020\022\022\024\n\020EmoServiceStopRQ" +
      "\020\023\022\024\n\020EmoServiceStopRP\020\024\022\024\n\020PhysioEmoRec" +
      "ogRQ\020\025\022\024\n\020SpeechEmoRecogRQ\020\026\022\022\n\016FaceEmoR" +
      "ecogRQ\020\027\022\024\n\020PhysioEmoRecogRP\020\030\022\024\n\020Speech" +
      "EmoRecogRP\020\031\022\022\n\016FaceEmoRecogRP\020\032\022\016\n\nEmoR" +
      "ecogRQ\020\033\022\016\n\nEmoRecogRP\020\034\022\017\n\013HeartBeatRQ\020" +
      "\035\022\017\n\013HeartBeatRP\020\036\022\030\n\024ErkMsgType_reserve" +
      "d1\020\037\022\030\n\024ErkMsgType_reserved2\020 *\312\001\n\021ErkIn" +
      "terMsgType_e\022\033\n\027ErkInterMsgType_unknown\020" +
      "\000\022\025\n\021ErkEngineCreateRQ\020\001\022\025\n\021ErkEngineCre" +
      "ateRP\020\002\022\025\n\021ErkEngineDeleteRQ\020\003\022\025\n\021ErkEng" +
      "ineDeleteRP\020\004\022\035\n\031ErkInterMsgType_reserve" +
      "d1\020\005\022\035\n\031ErkInterMsgType_reserved2\020\006*\300\003\n\014" +
      "ReturnCode_e\022\026\n\022ReturnCode_unknown\020\000\022\021\n\r" +
      "ReturnCode_ok\020\001\022\026\n\022ReturnCode_nok_Org\020\002\022" +
      "\027\n\023ReturnCode_nok_User\020\003\022\032\n\026ReturnCode_n" +
      "ok_MsgType\020\004\022\035\n\031ReturnCode_nok_EngineTyp" +
      "e\020\005\022\"\n\036ReturnCode_nok_EngineCondition\020\006\022" +
      "(\n$ReturnCode_nok_PhysioEngineCondition\020" +
      "\007\022(\n$ReturnCode_nok_SpeechEngineConditio" +
      "n\020\010\022)\n%ReturnCode_nok_FaceEmoEngineCondi" +
      "tion\020\t\022\036\n\032ReturnCode_nok_DevPlatform\020\n\022\036" +
      "\n\032ReturnCode_nok_EmotionType\020\013\022\032\n\026Return" +
      "Code_nok_reason1\020\014\022\032\n\026ReturnCode_nok_rea" +
      "son2\020\r*\331\001\n\014EngineType_e\022\026\n\022EngineType_un" +
      "known\020\000\022\031\n\025EngineType_physiology\020\001\022\025\n\021En" +
      "gineType_speech\020\002\022\023\n\017EngineType_face\020\003\022\034" +
      "\n\030EngineType_emo_recog_all\020\004\022\030\n\024EngineTy" +
      "pe_knowledge\020\005\022\030\n\024EngineType_reserved1\020\006" +
      "\022\030\n\024EngineType_reserved2\020\007*r\n\021EngineCond" +
      "ition_e\022\033\n\027EngineCondition_unknown\020\000\022\035\n\031" +
      "EngineCondition_available\020\001\022!\n\035EngineCon" +
      "dition_not_available\020\002*\355\002\n\rServiceType_e" +
      "\022\027\n\023ServiceType_unknown\020\000\022\032\n\026ServiceType" +
      "_physiology\020\001\022\026\n\022ServiceType_speech\020\002\022\025\n" +
      "\021ServiceType_video\020\003\022!\n\035ServiceType_phys" +
      "iology_speech\020\004\022 \n\034ServiceType_physiolog" +
      "y_video\020\005\022\034\n\030ServiceType_speech_video\020\006\022" +
      "\'\n#ServiceType_physiology_speech_video\020\007" +
      "\022\031\n\025ServiceType_knowledge\020\010\022\033\n\027ServiceTy" +
      "pe_service_all\020\t\022\031\n\025ServiceType_reserved" +
      "1\020\n\022\031\n\025ServiceType_reserved2\020\013*\263\003\n\rEmoti" +
      "onType_e\022\027\n\023EmotionType_unknown\020\000\022\027\n\023Emo" +
      "tionType_neutral\020\001\022\030\n\024EmotionType_positi" +
      "ve\020\002\022\030\n\024EmotionType_negative\020\003\022\026\n\022Emotio" +
      "nType_stress\020\004\022\023\n\017EmotionType_joy\020\005\022\025\n\021E" +
      "motionType_happy\020\006\022\027\n\023EmotionType_sadnes" +
      "s\020\007\022\025\n\021EmotionType_anger\020\010\022\027\n\023EmotionTyp" +
      "e_arousal\020\t\022\032\n\026EmotionType_relaxation\020\n\022" +
      "\025\n\021EmotionType_peace\020\013\022\027\n\023EmotionType_an" +
      "xiety\020\014\022\024\n\020EmotionType_fear\020\r\022\027\n\023Emotion" +
      "Type_disgust\020\016\022\031\n\025EmotionType_reserved1\020" +
      "\017\022\031\n\025EmotionType_reserved2\020\020*\344\002\n\022OrgProf" +
      "ileResult_e\022\034\n\030OrgProfileResult_unknown\020" +
      "\000\022\027\n\023OrgProfileResult_ok\020\001\022 \n\034OrgProfile" +
      "Result_nok_OrgName\020\002\022\037\n\033OrgProfileResult" +
      "_nok_OrgPwd\020\003\022(\n$OrgProfileResult_nok_Se" +
      "rviceDuration\020\004\022#\n\037OrgProfileResult_nok_" +
      "UserNumber\020\005\022$\n OrgProfileResult_nok_Ser" +
      "viceType\020\006\022\033\n\027OrgProfileResult_nok_DB\020\007\022" +
      " \n\034OrgProfileResult_nok_reason1\020\010\022 \n\034Org" +
      "ProfileResult_nok_reason2\020\t*\320\003\n\023UserProf" +
      "ileResult_e\022\035\n\031UserProfileResult_unknown" +
      "\020\000\022\030\n\024UserProfileResult_ok\020\001\022!\n\035UserProf" +
      "ileResult_nok_OrgName\020\002\022\"\n\036UserProfileRe" +
      "sult_nok_UserName\020\003\022!\n\035UserProfileResult" +
      "_nok_UserPwd\020\004\022)\n%UserProfileResult_nok_" +
      "ServiceDuration\020\005\022\035\n\031UserProfileResult_n" +
      "ok_Age\020\006\022\035\n\031UserProfileResult_nok_Sex\020\007\022" +
      "\"\n\036UserProfileResult_nok_UserType\020\010\022%\n!U" +
      "serProfileResult_nok_ServiceType\020\t\022\034\n\030Us" +
      "erProfileResult_nok_DB\020\n\022!\n\035UserProfileR" +
      "esult_nok_reason1\020\013\022!\n\035UserProfileResult" +
      "_nok_reason2\020\014*\243\003\n\016ProviderType_e\022\030\n\024Pro" +
      "viderType_unknown\020\000\022\031\n\025ProviderType_pers" +
      "onal\020\001\022\030\n\024ProviderType_medical\020\002\022\032\n\026Prov" +
      "iderType_education\020\003\022\036\n\032ProviderType_pub" +
      "lic_social\020\004\022 \n\034ProviderType_emotional_l" +
      "abor\020\005\022\031\n\025ProviderType_fire_119\020\006\022&\n\"Pro" +
      "viderType_communication_service\020\007\022\036\n\032Pro" +
      "viderType_advertisement\020\010\022%\n!ProviderTyp" +
      "e_construction_project\020\t\022\"\n\036ProviderType" +
      "_clothing_business\020\n\022\032\n\026ProviderType_res" +
      "erved1\020\013\022\032\n\026ProviderType_reserved2\020\014*t\n\t" +
      "SexType_e\022\023\n\017SexType_unknown\020\000\022\020\n\014SexTyp" +
      "e_male\020\001\022\022\n\016SexType_female\020\002\022\025\n\021SexType_" +
      "reserved1\020\003\022\025\n\021SexType_reserved2\020\004*\377\002\n\nU" +
      "serType_e\022\024\n\020UserType_unknown\020\000\022\023\n\017UserT" +
      "ype_normal\020\001\022\025\n\021UserType_disabled\020\002\022\025\n\021U" +
      "serType_dementia\020\003\022\023\n\017UserType_infant\020\004\022" +
      "\024\n\020UserType_student\020\005\022\024\n\020UserType_soldie" +
      "r\020\006\022\030\n\024UserType_firefighter\020\007\022\024\n\020UserTyp" +
      "e_farmers\020\010\022\026\n\022UserType_fishermen\020\t\022\025\n\021U" +
      "serType_merchant\020\n\022\031\n\025UserType_professio" +
      "nal\020\013\022\024\n\020UserType_teacher\020\014\022\027\n\023UserType_" +
      "politician\020\r\022\026\n\022UserType_reserved1\020\016\022\026\n\022" +
      "UserType_reserved2\020\017*\202\003\n\nMbtiType_e\022\024\n\020M" +
      "btiType_unknown\020\000\022\021\n\rMbtiType_ISTJ\020\001\022\021\n\r" +
      "MbtiType_ISFJ\020\002\022\021\n\rMbtiType_INFJ\020\003\022\021\n\rMb" +
      "tiType_INTJ\020\004\022\021\n\rMbtiType_ISTP\020\005\022\021\n\rMbti" +
      "Type_ISFP\020\006\022\021\n\rMbtiType_INFP\020\007\022\021\n\rMbtiTy" +
      "pe_INTP\020\010\022\021\n\rMbtiType_ESTP\020\t\022\021\n\rMbtiType" +
      "_ESFP\020\n\022\021\n\rMbtiType_ENFP\020\013\022\021\n\rMbtiType_E" +
      "NTP\020\014\022\021\n\rMbtiType_ESTJ\020\r\022\021\n\rMbtiType_ESF" +
      "J\020\016\022\021\n\rMbtiType_ENFJ\020\017\022\021\n\rMbtiType_ENTJ\020" +
      "\020\022\026\n\022MbtiType_reserved1\020\021\022\026\n\022MbtiType_re" +
      "served2\020\022B\036\n\032com.erksystem.protobuf.apiP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ErkMsgHead_s_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErkMsgHead_s_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkMsgHead_s_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgId", "UserId", });
    internal_static_ErkMsgDataHead_s_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ErkMsgDataHead_s_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkMsgDataHead_s_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgId", "UserId", });
    internal_static_ErkInterMsgHead_s_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ErkInterMsgHead_s_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkInterMsgHead_s_descriptor,
        new java.lang.String[] { "MsgType", "OrgId", "UserId", });
    internal_static_QueueInfo_s_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_QueueInfo_s_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueueInfo_s_descriptor,
        new java.lang.String[] { "ToQueueName", "FromQueueName", });
    internal_static_ErkEngineInfo_s_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ErkEngineInfo_s_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkEngineInfo_s_descriptor,
        new java.lang.String[] { "EngineType", "EngineCondition", "IpAddr", "ReceiveQueueName", "SendQueueName", });
    internal_static_AddServiceProviderInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AddServiceProviderInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddServiceProviderInfoRQ_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "OrgPwd", "ProviderType", "ServiceDuration", "UserNumber", "ServiceType", });
    internal_static_AddServiceProviderInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AddServiceProviderInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddServiceProviderInfoRP_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "ResultType", "OrgId", "OrgPwd", "ProviderType", "ServiceDuration", "UserNumber", "ServiceType", });
    internal_static_UpdateServiceProviderInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_UpdateServiceProviderInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateServiceProviderInfoRQ_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "OldOrgPwd", "OldProviderType", "OldServiceDuration", "OldUserNumber", "OldServiceType", "NewOrgPwd", "NewProviderType", "NewServiceDuration", "NewUserNumber", "NewServiceType", });
    internal_static_UpdateServiceProviderInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateServiceProviderInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateServiceProviderInfoRP_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "ResultType", "OldOrgPwd", "OldProviderType", "OldServiceDuration", "OldUserNumber", "OldServiceType", "NewOrgPwd", "NewProviderType", "NewServiceDuration", "NewUserNumber", "NewServiceType", });
    internal_static_DelServiceProviderInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_DelServiceProviderInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelServiceProviderInfoRQ_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "OrgPwd", });
    internal_static_DelServiceProviderInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DelServiceProviderInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelServiceProviderInfoRP_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "ResultType", });
    internal_static_AddUserInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_AddUserInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddUserInfoRQ_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "UserName", "UserPwd", "ServiceDuration", "Age", "Sex", "MbtiType", "UserType", "ServiceType", });
    internal_static_AddUserInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_AddUserInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddUserInfoRP_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "UserName", "ResultType", "UserId", "UserPwd", "ServiceDuration", "Age", "Sex", "MbtiType", "UserType", "ServiceType", });
    internal_static_UpdateUserInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_UpdateUserInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserInfoRQ_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "UserName", "OldUserPwd", "OldServiceDuration", "OldAge", "OldSex", "OldMbtiType", "OldUserType", "OldServiceType", "NewUserPwd", "NewServiceDuration", "NewAge", "NewSex", "NewMbtiType", "NewUserType", "NewServiceType", });
    internal_static_UpdateUserInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_UpdateUserInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserInfoRP_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "UserName", "ResultType", "OldUserPwd", "OldServiceDuration", "OldAge", "OldSex", "OldMbtiType", "OldUserType", "OldServiceType", "NewUserPwd", "NewServiceDuration", "NewAge", "NewSex", "NewMbtiType", "NewUserType", "NewServiceType", });
    internal_static_DelUserInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_DelUserInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelUserInfoRQ_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "UserName", "UserPwd", });
    internal_static_DelUserInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_DelUserInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelUserInfoRP_m_descriptor,
        new java.lang.String[] { "MsgType", "QueueInfo", "OrgName", "UserName", "ResultType", "Return", });
    internal_static_ErkServiceConnRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ErkServiceConnRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceConnRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", });
    internal_static_ErkServiceConnRP_m_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ErkServiceConnRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceConnRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", "ServiceType", });
    internal_static_ErkServiceDisConnRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_ErkServiceDisConnRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceDisConnRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ServiceType", });
    internal_static_ErkServiceDisConnRP_m_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_ErkServiceDisConnRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceDisConnRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", });
    internal_static_EmoServiceStartRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_EmoServiceStartRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoServiceStartRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ServiceType", });
    internal_static_EmoServiceStartRP_m_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_EmoServiceStartRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoServiceStartRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", "PhysioEngineInfo", "SpeechEngineInfo", "FaceEngineInfo", "KnowledgeEngineInfo", "ServiceEngineInfo", });
    internal_static_EmoServiceStopRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_EmoServiceStopRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoServiceStopRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ServiceType", "PhysioEngineReceiveQueueName", "PhysioEngineSendQueueName", "SpeechEngineReceiveQueueName", "SpeechEngineSendQueueName", "FaceEngineReceiveQueueName", "FaceEngineSendQueueName", "KnowledgeEngineReceiveQueueName", "KnowledgeEngineSendQueueName", });
    internal_static_EmoServiceStopRP_m_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_EmoServiceStopRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoServiceStopRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", "PhysioEngineInfo", "SpeechEngineInfo", "FaceEngineInfo", "KnowledgeEngineInfo", "ServiceEngineInfo", });
    internal_static_ErkEngineCreateRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_ErkEngineCreateRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkEngineCreateRQ_m_descriptor,
        new java.lang.String[] { "ErkInterMsgHead", "MsgTime", "ServiceType", "PhysioEngineReceiveQueueName", "PhysioEngineSendQueueName", "SpeechEngineReceiveQueueName", "SpeechEngineSendQueueName", "FaceEngineReceiveQueueName", "FaceEngineSendQueueName", "KnowledgeEngineReceiveQueueName", "KnowledgeEngineSendQueueName", });
    internal_static_ErkEngineCreateRP_m_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_ErkEngineCreateRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkEngineCreateRP_m_descriptor,
        new java.lang.String[] { "ErkInterMsgHead", "MsgTime", "ReturnCode", "PhysioEngineInfo", "SpeechEngineInfo", "FaceEngineInfo", "KnowledgeEngineInfo", "ServiceEngineInfo", });
    internal_static_ErkEngineDeleteRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_ErkEngineDeleteRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkEngineDeleteRQ_m_descriptor,
        new java.lang.String[] { "ErkInterMsgHead", "MsgTime", "ServiceType", "PhysioEngineReceiveQueueName", "PhysioEngineSendQueueName", "SpeechEngineReceiveQueueName", "SpeechEngineSendQueueName", "FaceEngineReceiveQueueName", "FaceEngineSendQueueName", "KnowledgeEngineReceiveQueueName", "KnowledgeEngineSendQueueName", });
    internal_static_ErkEngineDeleteRP_m_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_ErkEngineDeleteRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkEngineDeleteRP_m_descriptor,
        new java.lang.String[] { "ErkInterMsgHead", "MsgTime", "ReturnCode", "PhysioEngineInfo", "SpeechEngineInfo", "FaceEngineInfo", "KnowledgeEngineInfo", "ServiceEngineInfo", });
    internal_static_HeartBeatRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_HeartBeatRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "QueueName", });
    internal_static_HeartBeatRP_m_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_HeartBeatRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "Status", });
    internal_static_EmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_EmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_EmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_EmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_PhysioEmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_PhysioEmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PhysioEmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_PhysioEmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_PhysioEmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PhysioEmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_SpeechEmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_SpeechEmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechEmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_SpeechEmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_SpeechEmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechEmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_FaceEmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_FaceEmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaceEmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_FaceEmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_FaceEmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaceEmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_EmoRecogNoti_m_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_EmoRecogNoti_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogNoti_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_ErkApiMsg_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_ErkApiMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkApiMsg_descriptor,
        new java.lang.String[] { "AddServiceProviderInfoRQ", "AddServiceProviderInfoRP", "UpdateServiceProviderInfoRQ", "UpdateServiceProviderInfoRP", "DelServiceProviderInfoRQ", "DelServiceProviderInfoRP", "AddUserInfoRQ", "AddUserInfoRP", "UpdateUserInfoRQ", "UpdateUserInfoRP", "DelUserInfoRQ", "DelUserInfoRP", "ErkServiceConnRQ", "ErkServiceConnRP", "ErkServiceDisConnRQ", "ErkServiceDisConnRP", "EmoServiceStartRQ", "EmoServiceStartRP", "EmoServiceStopRQ", "EmoServiceStopRP", "ErkEngineCreateRQ", "ErkEngineCreateRP", "ErkEngineDeleteRQ", "ErkEngineDeleteRP", "HeartBeatRQ", "HeartBeatRP", "EmoRecogRQ", "EmoRecogRP", "PhysioEmoRecogRQ", "PhysioEmoRecogRP", "SpeechEmoRecogRQ", "SpeechEmoRecogRP", "FaceEmoRecogRQ", "FaceEmoRecogRP", "EmoRecogNoti", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
